mshell.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include `mshell.h`
Data Structures
struct memnod
Defines
#define __MSHELL__
#define MEMTAG 0xa55a
#define ALIGN_SIZE sizeof(double)
#define HDR_SIZE sizeof(MEMHDR)
#define RESERVE_SIZE
#define CLIENT_2_HDR(a) ((MEMHDR *) (((char *) (a)) - RESERVE_SIZE))
#define HDR_2_CLIENT(a) ((void *) (((char *) (a)) + RESERVE_SIZE))
#define Mem_Tag_Err(a) mem_tag_err(a, fil, lin)
Typedefs
typedef memnod MEMHDR
Functions
void mem_tag_err (void *, char *, int)
void mem_list_add (MEMHDR *)
void mem_list_delete (MEMHDR *)
void * mem_alloc (size_t size, char *fil, int lin)
void * mem_realloc (void *ptr, size_t size, char *fil, int lin)
char * mem_strdup (char *str, char *fil, int lin)
void mem_free (void *ptr, char *fil, int lin)
unsigned long Mem_Used (void)
void Mem_Display (FILE *fp)
Variables
unsigned long mem_size = 0
MEMHDR * memlist = NULL
Define Documentation
#define __MSHELL__
Definition at line 32 of file mshell.c.
#define ALIGN_SIZE sizeof(double)
Definition at line 64 of file mshell.c.
#define CLIENT_2_HDR(a) ((MEMHDR *) (((char *) (a)) - RESERVE_SIZE))
Definition at line 73 of file mshell.c.
Referenced by mem_free(), and mem_realloc().
#define HDR_2_CLIENT(a) ((void *) (((char *) (a)) + RESERVE_SIZE))
Definition at line 74 of file mshell.c.
Referenced by mem_alloc(), and mem_realloc().
#define HDR_SIZE sizeof(MEMHDR)
Definition at line 66 of file mshell.c.
#define Mem_Tag_Err(a) mem_tag_err(a, fil, lin)
Definition at line 88 of file mshell.c.
Referenced by mem_free(), and mem_realloc().
#define MEMTAG 0xa55a
Definition at line 41 of file mshell.c.
Referenced by mem_alloc(), Mem_Display(), mem_free(), and mem_realloc().
#define RESERVE_SIZE
Value:
(((HDR_SIZE + (ALIGN_SIZE-1)) / ALIGN_SIZE) \
* ALIGN_SIZE)
Definition at line 67 of file mshell.c.
Referenced by mem_alloc(), and mem_realloc().
Typedef Documentation
typedef struct memnod MEMHDR
Function Documentation
void* mem_alloc (size_t size, char * fil, int lin)
Definition at line 112 of file mshell.c.
References calloc, HDR_2_CLIENT, mem_list_add(), mem_size, MEM_WHERE, MEMTAG, memnod::mh_file, memnod::mh_line, memnod::mh_size, memnod::mh_tag, and RESERVE_SIZE.
Referenced by mem_strdup().
void Mem_Display (FILE * fp)
Definition at line 364 of file mshell.c.
References mem_size, MEMTAG, memnod::mh_file, memnod::mh_line, memnod::mh_next, memnod::mh_size, and memnod::mh_tag.
Referenced by mem_list_add(), mem_list_delete(), and mem_tag_err().
void mem_free (void * ptr, char * fil, int lin)
Definition at line 286 of file mshell.c.
References CLIENT_2_HDR, free, mem_list_delete(), mem_size, Mem_Tag_Err, MEM_WHERE, MEMTAG, memnod::mh_size, and memnod::mh_tag.
void mem_list_add (MEMHDR *) [static]
Definition at line 408 of file mshell.c.
References Mem_Display(), memnod::mh_next, and memnod::mh_prev.
Referenced by mem_alloc(), and mem_realloc().
void mem_list_delete (MEMHDR *) [static]
Definition at line 433 of file mshell.c.
References Mem_Display(), memnod::mh_next, and memnod::mh_prev.
Referenced by mem_free(), and mem_realloc().
void* mem_realloc (void * ptr, size_t size, char * fil, int lin)
Definition at line 167 of file mshell.c.
References CLIENT_2_HDR, HDR_2_CLIENT, mem_list_add(), mem_list_delete(), mem_size, Mem_Tag_Err, MEM_WHERE, MEMTAG, memnod::mh_file, memnod::mh_line, memnod::mh_size, memnod::mh_tag, realloc, and RESERVE_SIZE.
char* mem_strdup (char * str, char * fil, int lin)
Definition at line 241 of file mshell.c.
References mem_alloc(), and MEM_WHERE.
void mem_tag_err (void *, char *, int) [static]
Definition at line 463 of file mshell.c.
References Mem_Display().
unsigned long Mem_Used (void)
Definition at line 341 of file mshell.c.
References mem_size.
Variable Documentation
unsigned long mem_size = 0 [static]
Definition at line 77 of file mshell.c.
Referenced by mem_alloc(), Mem_Display(), mem_free(), mem_realloc(), and Mem_Used().
MEMHDR* memlist = NULL [static]
Definition at line 79 of file mshell.c.