mshell.h File Reference
Defines
#define MEM_LIST
#define MEM_WHERE
#define malloc(a) mem_alloc((a), __FILE__, __LINE__)
#define realloc(a, b) mem_realloc((a), (b), __FILE__, __LINE__)
#define free(a) mem_free((a), __FILE__, __LINE__)
#define strdup(a) mem_strdup((a), __FILE__, __LINE__)
#define calloc(a, b) malloc(((a)*(b)))
Functions
unsigned long Mem_Used (void)
void Mem_Display (FILE *)
void * mem_alloc (size_t, char *, int)
void * mem_realloc (void *, size_t, char *, int)
void mem_free (void *, char *, int)
char * mem_strdup (char *, char *, int)
Define Documentation
#define calloc(a, b) malloc(((a)*(b)))
Definition at line 40 of file mshell.h.
Referenced by mem_alloc().
#define free(a) mem_free((a), __FILE__, __LINE__)
Definition at line 38 of file mshell.h.
Referenced by mat_alloc(), mat_free(), and mem_free().
#define malloc(a) mem_alloc((a), __FILE__, __LINE__)
Definition at line 36 of file mshell.h.
Referenced by mat_alloc().
#define MEM_LIST
Definition at line 13 of file mshell.h.
#define MEM_WHERE
Definition at line 14 of file mshell.h.
Referenced by mem_alloc(), mem_free(), mem_realloc(), and mem_strdup().
#define realloc(a, b) mem_realloc((a), (b), __FILE__, __LINE__)
Definition at line 37 of file mshell.h.
Referenced by mem_realloc().
#define strdup(a) mem_strdup((a), __FILE__, __LINE__)
Definition at line 39 of file mshell.h.
Function Documentation
void* mem_alloc (size_t, char *, int)
Definition at line 112 of file mshell.c.
References calloc, HDR_2_CLIENT, mem_list_add(), mem_size, MEM_WHERE, MEMTAG, memnod::mh_file, memnod::mh_line, memnod::mh_size, memnod::mh_tag, and RESERVE_SIZE.
Referenced by mem_strdup().
void Mem_Display (FILE *)
Definition at line 364 of file mshell.c.
References mem_size, MEMTAG, memnod::mh_file, memnod::mh_line, memnod::mh_next, memnod::mh_size, and memnod::mh_tag.
Referenced by mem_list_add(), mem_list_delete(), and mem_tag_err().
void mem_free (void *, char *, int)
Definition at line 286 of file mshell.c.
References CLIENT_2_HDR, free, mem_list_delete(), mem_size, Mem_Tag_Err, MEM_WHERE, MEMTAG, memnod::mh_size, and memnod::mh_tag.
void* mem_realloc (void *, size_t, char *, int)
Definition at line 167 of file mshell.c.
References CLIENT_2_HDR, HDR_2_CLIENT, mem_list_add(), mem_list_delete(), mem_size, Mem_Tag_Err, MEM_WHERE, MEMTAG, memnod::mh_file, memnod::mh_line, memnod::mh_size, memnod::mh_tag, realloc, and RESERVE_SIZE.
char* mem_strdup (char *, char *, int)
Definition at line 241 of file mshell.c.
References mem_alloc(), and MEM_WHERE.
unsigned long Mem_Used (void)
Definition at line 341 of file mshell.c.
References mem_size.